### ISSUE TITLE
Launch Bitcoin fails on MacOS 10.14

### ISSUE THREAD

**Issue by brentkearney** [lightning-power-users/node-launcher#85] opened 2018-12-24 15:18 UTC
The launcher window opens, I can select the data directory, but pressing the "Launch Bitcoin" button appears to do nothing. The console logs have:

error	10:14:07.129546 -0500	Node.Launcher.app	nw_path_close_fd Failed to close guarded necp fd 13 [9: Bad file descriptor]

**Comment by PierreRochard** [comment] 2018-12-26 01:02
If you or anyone stumbling on this thread knows how to reproduce this bug, it'll help me fix it! That's a strange error that I haven't seen reported yet

**Comment by ben-kaufman** [comment] 2019-01-12 07:30
Hi, couldn't reproduce that with the same OS version (MacOS 10.14.2), but I can keep trying.
@brentkearney could you please share the path to the data directory you selected?

**Comment by brentkearney** [comment] 2019-01-12 23:53
Doing some Googling for that obscure 'nw_path_close_fd...' error lead me to a thread on a Pascal IDE forum. I think the error has something to do with code signing and Mojave sandbox requirements. I registered an account on the forum and replied to the developer who posted about that error (all he said was how unhelpful the message is!), to ask if he had any insight on what it means and/or what causes it.

**Comment by PierreRochard** [comment] 2019-02-02 23:03
I haven't had anyone else report this problem yet, closing until we get more information. Thank you for the info!

**Closed by PierreRochard** 2019-02-02 23:03 UTC
Labels: bug

**Comment by brentkearney** [comment] 2019-03-10 01:25
I figured it out! It was Sophos Anti-virus blocking access. 🤦‍♂️

https://github.com/bitcoin/bitcoin/issues/15480#issuecomment-471237266
