### ISSUE TITLE
LND never finishes sync.

### ISSUE THREAD

**Issue by arvicco** [lightning-power-users/node-launcher#67] opened 2018-12-18 11:17 UTC
Macos 10.13.6, clean install everything from 5.1.1 release. LND is never able to finish sync, and getinfo always reports "synced_to_chain": false.

-----
2018-12-18 18:08:28.794 [INF] LTND: Version: 0.5.1-beta commit=, build=production, logging=default
2018-12-18 18:08:28.794 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2018-12-18 18:08:28.795 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2018-12-18 18:08:28.803 [INF] RPCS: password RPC server listening on 127.0.0.1:10010
2018-12-18 18:08:28.803 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8081
2018-12-18 18:08:28.803 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2018-12-18 18:08:38.417 [INF] LNWL: Opened wallet
2018-12-18 18:08:38.474 [INF] LTND: Primary chain is set to: bitcoin
2018-12-18 18:08:38.477 [INF] LTND: Initializing bitcoind backed fee estimator
2018-12-18 18:08:38.477 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://127.0.0.1:18503
2018-12-18 18:08:38.477 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://127.0.0.1:18502
2018-12-18 18:08:39.105 [INF] LNWL: The wallet has been unlocked without a time limit
2018-12-18 18:08:39.106 [INF] LTND: LightningWallet opened
2018-12-18 18:08:39.110 [INF] LNWL: Started rescan from block 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f (height 0) for 3 addresses
2018-12-18 18:08:39.110 [INF] LNWL: Starting rescan from block 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
2018-12-18 18:08:39.110 [INF] HSWC: Restoring in-memory circuit state from disk
2018-12-18 18:08:39.111 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
2018-12-18 18:08:39.112 [INF] RPCS: RPC server listening on 127.0.0.1:10010
2018-12-18 18:08:39.112 [INF] RPCS: gRPC proxy started at 127.0.0.1:8081
2018-12-18 18:08:39.113 [INF] LTND: Waiting for chain backend to finish sync, start_height=554344
2018-12-18 18:09:10.084 [INF] LNWL: Rescan finished at 0 (000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f)
2018-12-18 18:09:10.085 [ERR] LNWL: Unable to complete chain rescan: Post http://127.0.0.1:8332: dial tcp 127.0.0.1:8332: connect: operation timed out
2018-12-18 18:09:10.085 [INF] LNWL: Catching up block hashes to height 0, this might take a while
2018-12-18 18:09:10.085 [INF] LNWL: Done catching up block hashes
2018-12-18 18:09:10.086 [INF] LNWL: Finished rescan for 3 addresses (synced to block 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, height 0)
2018-12-18 18:09:33.406 [ERR] LNWL: Failed to process consensus server notification (name: `blockconnected`, detail: `failed to store sync information 0000000000000000002ae9ee04124233376d3a608d702866213613b5163fb0d9: failed to fetch block hash for height 554344: block not found`)
2018-12-18 18:11:41.757 [ERR] LNWL: Failed to process consensus server notification (name: `blockconnected`, detail: `failed to store sync information 0000000000000000001ee8666d4453b3b1da908c5cd12a47b9b4ef16a7f78372: failed to fetch block hash for height 554345: block not found`)

**Comment by PierreRochard** [comment] 2018-12-18 15:43
I've had this problem too, repeatedly closing LND, launching it again, and unlocking the wallet worked for me 

Wish I had a better solution, I'll keep this issue open as I figure out what's going on

Thank you for submitting the issue!

**Comment by arvicco** [comment] 2018-12-18 16:10
Cool, thanks, Pierre! Possibly, it's related to https://github.com/lightningnetwork/lnd/issues/1909 but I'm not really sure...

**Comment by arvicco** [comment] 2018-12-18 17:35
After restarting LND a few times, it finally started syncing. Since this is clearly a workaround not a proper solution, let's keep this issue open...

**Comment by brunocvcunha** [comment] 2019-01-10 19:41
It seems that restart after the initial scan should always be done & recommended. There's this and also I was just able to reproduce this error where ZMQ missed a block and just fixed it by restarting `lnd`: https://github.com/lightningnetwork/lnd/issues/1597

**Comment by minornode** [comment] 2019-03-29 14:14
I have a similar issue but I'm confident I'm doing something wrong here and it's not really an issue. I just can't figure out what exactly...

Bitcoind and Lnd were offline for a good month. I recently fired up my bitcoind again and it is fully synced. However, I am running this behind a VPN now (i.e. not visible on Bitnodes)

Lnd hangs on 'LTND: Waiting for chain backend to finish sync, start_height=569319'

Python shell in the background throws recurring error messages:

'E0329 15:13:42.649000000 19424 src/core/tsi/ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.'

So there is an issue with my certificates but I can't find enough online to fix this myself. Any thoughts?

**Comment by PierreRochard** [comment] 2019-03-29 16:26
@minornode 
Close LND
Click on the Show Macaroons button, keep going up the parent directories until you find the Lnd directory. If Show Macaroons is greyed out go to %localappdata%/Lnd on Windows or ~/Library/Application Support/Lnd on macOS
Delete the tls.cert and tls.key files
Start LND

**Comment by minornode** [comment] 2019-03-29 16:31
Tried this a few times already using the 'Reset TLS' button under Advanced without avail. Tried manually but the OPENSSL error is still there

**Comment by HelgeHunding** [comment] 2019-03-30 08:47
If you use a VPN, try turning it off for your local network. Might cause issues. Or simply turn it off  completely and try again (for debugging). To make sure that it's not the problem.

**Comment by minornode** [comment] 2019-03-30 12:30
Seems to be resolved.

Steps taken:
Reboot
Disabled VPN
Reset router + port forwarding
Reset TLS certificates
Restarted LND a couple of times

**Closed** 2019-04-03 01:01 UTC
Labels: bug
