### ISSUE TITLE
Fatal error detected

### ISSUE THREAD

**Issue by Zeno78** [lightning-power-users/node-launcher#269] opened 2019-04-09 22:53 UTC
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  -  [X] support request

* **What is the current behavior?**

running windows node launcher get "Failed to execute script pyi_rth_qt5plugins"

* **If the current behavior is a bug, please provide the steps to reproduce**

Run exe

* **What is the expected behavior?**

program run

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows  ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Zeno78** [comment] 2019-04-09 23:10
Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.2

Error information:

'NoneType' object has no attribute 'split'
File "node_launcher\node_set\lnd.py", line 192, in config_file_changed

**Comment by PierreRochard** [comment] 2019-04-09 23:40
Thank you for reporting it! This was likely caused by opening the Node Launcher several times

Fixed by https://github.com/lightning-power-users/node-launcher/commit/adf25fc0f81760e52d15c532452548b8f400895f

**Closed by PierreRochard** 2019-04-09 23:40 UTC
